apiVersion: 1
datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: reformmed
    secureJsonData:
      password: "monitor2345"
    jsonData:
      database: monitor_machine
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 10
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
    editable: true
    version: 3
